### ISSUE TITLE
Create list of engines-to-benchmark

### ISSUE THREAD

**Issue by lrettig** [ewasm/benchmarking#20]
We are aware of the following engines but have not run benchmarks on them yet, along with some further notes/thoughts on each:

* `lucet` - A Wasm compiler from Fastly. https://github.com/fastly/lucet
    * Early indications are that this engine is highly performant but it's quite new and didn't make it into this round of benchmarks.
    * Optimized for fast instantiation, fast startup, and short runtimes
    * Uses `cranelift`.

* `lightbeam` - An experimental, one-pass streaming compiler intended for use in `wasmtime`. https://github.com/CraneStation/lightbeam

* `wasmer` https://github.com/wasmerio/wasmer
    * `wasmer` is kind of a wrapper around three engines: `wasmtime` (which is already benchmarked separately), `lightbeam`, and `WAVM`. The wasmer docs don't say this explicitly, but it uses the same libraries as the other engines:
    * `wasmtime` depends on `cranelift`, and wasmer imports cranelift
    * `lightbeam` depends on `dynasm`, and wasmer imports dynasm
    * `WAVM` depends llvm, and wasmer depends on llvm through some rust-llvm bindings called `inkwell`.

* `binaryen` - A wasm interpreter written in C++. The Binaryen toolchain is used by [emscripten](https://github.com/emscripten-core/emscripten) for compiling C/C++ to wasm and asm.js (more specifically, for compiling LLVM bitcode to wasm). https://github.com/WebAssembly/binaryen
    * Binaryen appears in a later section of the report, the Ewasm benchmarks section / metering, because it is integrated into Hera.

* `wag`

**Comment by jwasinger** [comment]
Can this be closed?

**Comment by lrettig** [comment]
I'm probably not the right person to ask :)
