### ISSUE TITLE
Add instructions for Wasm benchmarks with host functions

### ISSUE THREAD

**Issue by hjorthjort** [ewasm/benchmarking#21]
Looks like the repo is only EVM benchmarks for now. I would like to see the Wasm code you ran to get the Wasm statistics (wabt, wabt-with-bignum, v8-turbofan, v8-liftoff) that was shown at Devcon V.

**Comment by axic** [comment]
The repository has been updated with a lot of scripts with all the details. You can check the `scout-engines` and `wasm-engines/docker` directory for the docker files linking to the sources.

Let us know what exact details you are interested in so we can expand the description.

**Comment by axic** [comment]
@hjorthjort let me know if there's more we should document and we can reopen this.
