### ISSUE TITLE
Change Scout images to use build-bench-base / llvm-10

### ISSUE THREAD

**Issue by axic** [ewasm/benchmarking#64]
This should only focus on changing `scout-engines/Dockerfile`  to use `ewasm/llvm-10:1` as a base and remove all the "workarounds" off installing cmake, llvm, etc.

**Comment by jwasinger** [comment]
suggest basing https://github.com/ewasm/benchmarking/blob/master/scout-engines/Dockerfile of bench-build-base, moving to a multistage to reduce size.
